config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resource :accounts, only: [:edit] do
    member do
      get 'edit_password'
      patch 'update_password'
      post 'enable_two_factor'
      delete 'disable_two_factor'
    end
  end

  get '/login/otp', to: 'sessions#login_otp', as: :login_otp
  post '/verify_otp', to: 'sessions#verify_otp', as: :verify_otp
  get '/dashboard', to: 'home#dashboard', as: :dashboard
  delete '/logout', to: 'sessions#destroy', as: :logout
  get 'confirm_email/:token', to: 'users#confirm_email', as: 'confirm_email'
  root to: 'users#new'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_create :generate_otp_secret_key

  attr_accessor :confirmation_token
  
  validates :otp_secret_key, presence: true, if: :two_fa_enabled?
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:password] }

  def generate_otp_secret_key
    self.confirmation_token = SecureRandom.urlsafe_base64
  end

  def enable_two_factor_authentication
    generate_otp_secret_key
    update(two_fa_enabled: true)
  end

  def send_otp
    client = Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])

    otp = generate_otp
    message = "Your OTP: #{otp}"

    client.messages.create(
      from: 'your_twilio_phone_number',
      to: phone_number,
      body: message
    )

    puts "Your OTP: #{generate_otp}"
  end

  def verify_otp(otp)
    ROTP::TOTP.new(otp_secret_key).verify(otp)
  end

  private

  def generate_otp
    ROTP::TOTP.new(otp_secret_key).now
  end
end

app/controllers/accounts_controller.rb
# app/controllers/account_controller.rb
class AccountsController < ApplicationController
  before_action :require_login, only: [:edit, :update_password, :enable_two_factor, :disable_two_factor]

  def edit
  end

  def edit_password
  end

  def update_password
    if current_user&.authenticate(params[:user][:current_password])
      if current_user.update(password: params[:user][:new_password])
        redirect_to edit_accounts_path, notice: 'Password updated successfully.'
      else
        flash.now[:alert] = 'Failed to update password.'
        render :edit
      end
    else
      flash.now[:alert] = 'Current password is incorrect.'
      render :edit
    end
  end

  def enable_two_factor
    current_user.enable_two_factor_authentication
    redirect_to edit_accounts_path, notice: 'Two-factor authentication enabled. Scan the QR code with your authenticator app.'
  end

  def disable_two_factor
    current_user.update(two_fa_enabled: false, otp_secret_key: nil)
    redirect_to edit_accounts_path, notice: 'Two-factor authentication disabled.'
  end

  private

  def require_login
    unless logged_in?
      redirect_to root_path, alert: 'You must be logged in to access this page.'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
# app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login

  def dashboard
  end

  private

  def require_login
    unless logged_in?
      redirect_to root_path, alert: 'You must be logged in to access this page.'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      if @user.two_fa_enabled?
        session[:two_factor] = true
        @user.generate_otp_secret_key
        @user.send_otp
        redirect_to login_otp_path
      else
        log_in @user
        redirect_to dashboard_path, notice: 'Logged in successfully.'
      end
    else
      flash.now[:alert] = 'Invalid email or password.'
      render :new
    end
  end

  def login_otp
    # This is a placeholder action, render a form for the user to enter the OTP
  end

  def verify_otp
    if session["two_factor"]
      entered_otp = params[:session]["otp"]
      if current_user&.verify_otp(entered_otp)
        log_in current_user
        session.delete(:two_factor)
        redirect_to dashboard_path, notice: 'Two-factor authentication successful.'
      else
        flash.now[:alert] = 'Invalid OTP. Please try again.'
        render :login_otp
      end
    else
      redirect_to root_path, alert: 'Invalid request.'
    end
  end

  def destroy
    log_out
    redirect_to root_path, notice: 'Logged out successfully.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Send confirmation email
      UserMailer.confirmation_email(@user).deliver_now
      redirect_to root_path, notice: 'User Successfully Created! Please check your email for confirmation instructions.'
    else
      render :new
    end
  end

  def confirm_email
    user = User.find_by(confirmation_token: params[:confirmation_token])
    if user
      user.update(confirmed: true)
      redirect_to root_path, notice: 'Email confirmed successfully.'
    else
      redirect_to root_path, alert: 'Invalid confirmation token.'
    end
  end

  def enable_otp
    current_user.two_fa_enabled
    # Assume you have a method to display the QR code to the user
    render :show_qr_code
  end

  def show_qr_code
    # Display the QR code to the user using the otp_provisioning_uri method
    @qr_code_uri = current_user.otp_provisioning_uri
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/accounts/edit.html.erb
<!-- app/views/account/edit.html.erb -->
<h2>Account Settings</h2>

<% if current_user.two_fa_enabled? %>
  <p>Two-Factor Authentication: Enabled</p>
  <%= link_to 'Disable Two-Factor Authentication', disable_two_factor_accounts_path, method: :delete %><br/>
<% else %>
  <p>Two-Factor Authentication: Disabled</p>
  <%= link_to 'Enable Two-Factor Authentication', enable_two_factor_accounts_path, method: :post %><br/>
<% end %>

<%= link_to 'Update Password', update_password_accounts_path, method: :patch %><br/>

<%= link_to 'Logout', logout_path, method: :delete %><br/>

app/views/accounts/edit_password.html.erb
<!-- app/views/accounts/edit_password.html.erb -->
<h2>Edit Password</h2>

<%= form_for :user, url: update_password_accounts_path, method: :patch do |form| %>
  <%= form.label :current_password %>
  <%= form.password_field :current_password %>

  <%= form.label :new_password %>
  <%= form.password_field :new_password %>

  <%= form.label :new_password_confirmation %>
  <%= form.password_field :new_password_confirmation %>

  <%= form.submit 'Update Password' %>
<% end %>

app/views/home/dashboard.html.erb
<!-- app/views/home/dashboard.html.erb -->
<h2>Welcome to Your Dashboard</h2>

<p>Hello, <%= current_user.email %>!</p>


<%= link_to 'Change Password', edit_password_accounts_path %><br/>
<%= link_to 'Logout', logout_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwoFactorAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <% flash.each do |type, message| %>
    <div class="alert <%= type %>">
      <%= message %>
    </div>
  <% end %>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Please Register</h1>

<%= form_for @user do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %><br/><br/>

  <%= f.label :password %>
  <%= f.password_field :password %><br/><br/>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br/><br/>

  <%= f.submit "Register" %>
<% end %><br/>
Alredy have Account:  <%= link_to 'Login Please', new_session_path %>

app/views/users/show_qr_code.html.erb
<!-- app/views/users/show_qr_code.html.erb -->

<h1>Two-Factor Authentication Setup</h1>
<% if @qr_code_uri %>
  <%= image_tag @qr_code_uri %>
<% else %>
  <p>Two-Factor Authentication is not enabled.</p>
<% end %>